---
name: Install Linuxbrew
description: Installs Linuxbrew and updates apt-get with build-essentials

runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@v1
    - name: Cache Linuxbrew
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/Homebrew
          /home/linuxbrew/.linuxbrew/
        key: ${{ runner.os }}-linuxbrew-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Linuxbrew
      shell: bash
      # yamllint disable rule:line-length
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
        test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        set -xeuo pipefail
        echo "PATH=${PATH}" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$(brew --prefix)/lib" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(brew --prefix)/lib" >> $GITHUB_ENV
        if [ "$EUID" -ne 0 ]; then
          sudo apt-get update
          sudo apt-get install build-essential
        else
          apt-get update
          apt-get install build-essential
        fi
      # yamllint enable
