[package]
name = "nes"
version = "0.1.0"
authors = ["Luke Petherbridge <lukexor@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
gl = "0.12.0"
glfw = { version = "0.27.0", features = ["image"] }
image = "0.21.1"
sha2 = "0.8.0"
dirs = "1.0.5"
