[package]
name = "rustynes"
version = "0.5.0"
license = "GPL-3.0-or-later"
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/rustynes"
repository = "https://github.com/lukexor/rustynes.git"
homepage = "https://github.com/lukexor/rustynes"
edition = "2018"

[dependencies]
chrono = "0.4.11"
dirs = "2.0.2"
include_dir = "0.5.0"
enum_dispatch = { path = "lib/enum_dispatch" }
pix-engine = { version = "0.3.3", default_features = false }
png = "0.16.1"
rand = "0.7.3"
structopt = "0.3.12"
wasm-bindgen = { version = "0.2.59", optional = true }

[features]
default = ["sdl2-driver"]
sdl2-driver = ["pix-engine/sdl2-driver"]
wasm-driver = ["pix-engine/wasm-driver", "wasm-bindgen"]
no-randomize-ram = []

[profile.dev]
opt-level = 2

[profile.release]
# debug = true
lto = true
codegen-units = 1
panic = 'abort'

[profile.test]
opt-level = 2
