[package]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["emulators", "wasm"]
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
documentation = "https://docs.rs/tetanes"
edition = "2021"
keywords = ["nes", "emulator", "wasm"]
license = "GPL-3.0-or-later"
name = "tetanes"
repository = "https://github.com/lukexor/tetanes.git"
resolver = "2"
version = "0.8.0"
default-run = "tetanes"
exclude = ["/static", "/test_roms", "/docs"]

[package.metadata]
msrv = "1.56.1"

[dependencies]
bitflags = "1.2.1"
chrono = "0.4.19"
dirs = "4.0.0"
enum_dispatch = "0.3.7"
lazy_static = "1.4.0"
log = "0.4.14"
pix-engine = { version = "0.5.2", features = ["serde"] }
pretty_env_logger = "0.4.0"
rand = "0.8.4"
structopt = "0.3.25"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
anyhow = "1.0.50"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.78"

[patch.crates-io]
pix-engine = { path = "../pix-engine" }

[features]
default = ["pix-engine/use-vcpkg"]

[profile.dev-opt]
inherits = "dev"
opt-level = 2

[profile.release]
codegen-units = 1
lto = true

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-image[libjpeg-turbo,tiff,libwebp]", "sdl2-ttf", "sdl2-gfx", "sdl2-mixer"]
git = "https://github.com/microsoft/vcpkg"
rev = "2a31089e777fc187f1cc05338250b8e1810cfb52"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
