[package]
name = "tetanes"
version = "0.8.0"
license = "GPL-3.0-or-later"
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
categories = ["emulators", "wasm"]
keywords = ["nes", "emulator", "wasm"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/tetanes#readme"
repository = "https://github.com/lukexor/tetanes.git"
homepage = "https://github.com/lukexor/tetanes"
edition = "2018"
resolver = "2"
default-run = "tetanes"

[dependencies]
chrono = "0.4.19"
dirs = "3.0.2"
enum_dispatch = "0.3.7"
lazy_static = "1.4.0"
log = "0.4.14"
pix-engine = { version = "0.4.0", features = ["serde"] }
png = "0.16.8"
pretty_env_logger = "0.4.0"
rand = "0.8.4"
structopt = "0.3.22"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.74"

[patch.crates-io]
pix-engine = { path = "../pix-engine" }

[profile.dev]
opt-level = 2
split-debuginfo = "unpacked"

[profile.test]
opt-level = 2

[profile.release]
codegen-units = 1
lto = true
