[package]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["emulators", "wasm"]
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
documentation = "https://docs.rs/tetanes"
edition = "2021"
keywords = ["nes", "emulator", "wasm"]
license = "GPL-3.0-or-later"
name = "tetanes"
repository = "https://github.com/lukexor/tetanes.git"
resolver = "2"
version = "0.8.0"
default-run = "tetanes"
exclude = ["/bin", "/static", "/test_roms", "/docs", "/test_results"]

[package.metadata]
msrv = "1.59.0"

[dependencies]
bitflags = "1.2.1"
chrono = "0.4.19"
dirs = "4.0.0"
enum_dispatch = "0.3.7"
lazy_static = "1.4.0"
log = { version = "0.4.14", features = ["release_max_level_warn", "serde"] }
pretty_env_logger = "0.4.0"
rand = "0.8.4"
structopt = "0.3.25"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.72"
anyhow = "1.0.53"
bincode = "1.3.3"
flate2 = "1.0.24"
ringbuf = "0.2.6"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["user-hooks"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pix-engine = { version = "0.5.4", features = ["serde"] }

[patch.crates-io]
pix-engine = { git = "https://github.com/lukexor/pix-engine.git" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Required because of downstream dependencies: https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2.7", features = ["js"] }
wasm-bindgen = "0.2.81"

[features]
default = []

[profile.dev-opt]
inherits = "dev"
opt-level = 2

[profile.test]
inherits = "dev-opt"

[profile.release]
codegen-units = 1
lto = true
