[package]
name = "tetanes"
version = "0.7.0"
license = "GPL-3.0-or-later"
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
categories = ["emulators", "wasm"]
keywords = ["nes", "emulator", "wasm"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/tetanes#readme"
repository = "https://github.com/lukexor/tetanes.git"
homepage = "https://github.com/lukexor/tetanes"
edition = "2018"
default-run = "tetanes"

[dependencies]
chrono = "0.4"
dirs = "3.0"
enum_dispatch = "0.3"
include_dir = "0.6"
lazy_static = "1.4"
log = "0.4"
pix-engine = { version = "0.3", default_features = false }
png = "0.16"
pretty_env_logger = "0.4"
rand = "0.8"
structopt = "0.3"
wasm-bindgen = { version = "0.2", optional = true }

[features]
default = ["sdl2-driver"]
sdl2-driver = ["pix-engine/sdl2-driver"]
wasm-driver = ["pix-engine/wasm-driver", "wasm-bindgen"]
no-randomize-ram = []

[profile.dev]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1

[profile.test]
opt-level = 2
