[package]
name = "rustynes"
version = "0.1.0"
authors = ["Luke Petherbridge <lukexor@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.5"
failure = "0.1.5"
image = "0.21.1"
sdl2 = { version = "0.32.2", features = ["image"] }
sha2 = "0.8.0"
structopt = "0.2"
