[package]
name = "rustynes"
version = "0.1.0"
authors = ["Luke Petherbridge <lukexor@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.5"
failure = "0.1.5"
image = "0.21.1"
sdl2 = "0.32.2"
sha2 = "0.8.0"
structopt = "0.2"
chrono = "0.4.6"
rand = "0.6.5"
