[package]
name = "rustynes"
version = "0.4.0"
license = "GNU"
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/rustynes"
repository = "https://github.com/lukexor/rustynes.git"
homepage = "https://github.com/lukexor/rustynes"
edition = "2018"

[dependencies]
dirs = "2.0.2"
structopt = "0.3.1"
chrono = "0.4.9"
rand = "0.7.1"
png = "0.15.0"
pix-engine = { path = "lib/pix-engine", default_features = false }

[features]
default = ["sdl2-driver"]
sdl2-driver = ["pix-engine/sdl2-driver"]
wasm-driver = ["pix-engine/wasm-driver"]

[profile.dev]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
