[package]
name = "nes"
version = "0.1.0"
authors = ["Luke Petherbridge <lukexor@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
byteorder = "1.3.1"
glfw = { version = "0.27.0", features = ["image"] }
gl = "0.12.0"
