[package]
name = "tetanes"
version = "0.8.0"
license = "GPL-3.0-or-later"
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
categories = ["emulators", "wasm"]
keywords = ["nes", "emulator", "wasm"]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://github.com/lukexor/tetanes#readme"
repository = "https://github.com/lukexor/tetanes.git"
homepage = "https://github.com/lukexor/tetanes"
edition = "2018"
resolver = "2"
default-run = "tetanes"

[dependencies]
chrono = "^0.4"
dirs = "^3.0"
enum_dispatch = "^0.3"
lazy_static = "^1.4"
log = "^0.4"
pix-engine = { version = "^0.4", features = ["serde"] }
png = "^0.16"
pretty_env_logger = "^0.4"
rand = "^0.8"
structopt = "^0.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0.2"

[patch.crates-io]
pix-engine = { path = "../pix-engine" }

[features]
no-randomize-ram = []

[profile.dev]
opt-level = 2
split-debuginfo = "unpacked"

[profile.release]
lto = true
codegen-units = 1

[profile.test]
opt-level = 2
