[package]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["emulators", "wasm"]
description = "A NES Emulator written in Rust with SDL2 and WebAssembly support"
documentation = "https://docs.rs/tetanes"
edition = "2021"
keywords = ["nes", "emulator", "wasm"]
license = "GPL-3.0"
name = "tetanes"
repository = "https://github.com/lukexor/tetanes.git"
resolver = "2"
version = "0.8.0"
default-run = "tetanes"
exclude = ["/bin", "/static", "/test_roms", "/docs", "/test_results"]

[package.metadata]
msrv = "1.70.0"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
bitflags = { version = "2.4", features = ["serde"] }
chrono = "0.4"
dirs = "5.0"
enum_dispatch = "0.3"
flate2 = "1.0"
log = { version = "0.4", features = ["release_max_level_warn", "serde"] }
once_cell = "1.16"
pretty_env_logger = "0.5"
rand = "0.8"
ringbuf = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"

[dev-dependencies.cargo-husky]
version = "1.5"
default-features = false
features = ["user-hooks"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pix-engine = { version = "0.7", features = ["serde"] }

[patch.crates-io]
pix-engine = { git = "https://github.com/lukexor/pix-engine.git" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Required because of downstream dependencies: https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"

[features]
default = ["cycle-accurate"]
cycle-accurate = []
profile-rate-control = []

# Optimized development for playable framerates
[profile.dev-opt]
inherits = "dev"
opt-level = 2

[profile.test]
inherits = "dev-opt"

[profile.release]
codegen-units = 1
lto = true
