---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all --check

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [stable, 1.70.0]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: ./.github/actions/install-linuxbrew
        if: matrix.os == 'ubuntu-latest'
        name: Install Homebrew for Linux
      - uses: ./.github/actions/install-sdl2
        if: matrix.os != 'windows-latest'
        name: Install SDL2
      - name: Install wasm-pack
        if: matrix.os != 'windows-latest'
        shell: bash
        run: cargo install wasm-pack
      - name: Build
        shell: bash
        run: |
          cargo build --all-targets --verbose
          cd web
          bash bin/build.sh --dev
      - run: cargo doc --verbose
      - run: cargo test --verbose
