---
name: Outdated

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "10 16 * * 1"

env:
  CARGO_TERM_COLOR: always

jobs:
  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --exit-code 1
