---
name: Cargo Publish

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
      - uses: Swatinem/rust-cache@v2
      - uses: ./.github/actions/install-sdl2
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
